language: php

sudo: false

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - composer test
