name: Tests

on:
  push:
    branches: [5.x]
  pull_request:
  schedule:
    - cron: '0 9 * * *'

concurrency:
  group: tests-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    if: github.event_name != 'schedule' || github.repository == 'pestphp/pest'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest
        symfony: ['8.0']
        php: ['8.4', '8.5']
        dependency_version: [prefer-stable]

    name: PHP ${{ matrix.php }} - Symfony ^${{ matrix.symfony }} - ${{ matrix.os }} - ${{ matrix.dependency_version }}

    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: none
        extensions: sockets

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('**/composer.json', '**/composer.lock') }}
        restore-keys: |
          ${{ matrix.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-
          ${{ matrix.os }}-php-${{ matrix.php }}-composer-

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      shell: bash
      env:
        COMPOSER_ROOT_VERSION: 4.x-dev
      run: composer update --${{ matrix.dependency_version }} --no-interaction --no-progress --ansi --with="symfony/console:^${{ matrix.symfony }}"

    - name: Unit Tests
      run: composer test:unit

    - name: Parallel Tests
      run: composer test:parallel

    - name: Integration Tests
      run: composer test:integration
